In [52]:
import pandas as pd
import numpy as np

df_clean = pd.read_csv('it_services_tickets_raw.csv', low_memory=False)


# resolution time hours was left as text in the pandas notebook - convert it here
df_clean['resolution time hours'] = pd.to_numeric(df_clean['resolution time hours'], errors='coerce')

matrix = df_clean[
    ['hours_logged', 'Billing Rate (USD)', 'Billable Amount USD', 'resolution time hours', 'CSAT Score']
].to_numpy()

matrix.shape

(49588, 5)

**Q1. Import NumPy and print its version.**

In [53]:
print(np.__version__)

2.1.3


*NumPy is imported and ready to use.*

**Q2. Make an array from the hours logged column.**

In [54]:
hours = matrix[:, 0]
hours[:10]

array(['?', '1.34 ', '7', '34.630', '12.76 ', '15.30', '--', '9', '1.660',
       '11.1 hrs'], dtype=object)

*`hours` is now a 1-D NumPy array pulled straight out of the reference matrix's first column.*

**Q3. Print the shape, the size and the data type of that array.**

In [55]:
print("Shape:", hours.shape)
print("Size:", hours.size)
print("Dtype:", hours.dtype)

Shape: (49588,)
Size: 49588
Dtype: object


*`hours` is a one-dimensional array of floating-point numbers, one value per ticket.*

[link text](https:// [link text](https://))**Q4. Make an array of the numbers 1 to 50 using arange.**

In [56]:
arr_1_to_50 = np.arange(1, 51)
arr_1_to_50

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

*`np.arange(1, 51)` gives every whole number from 1 up to and including 50.*

**Q5. Make 10 evenly spaced numbers between 0 and 100 using linspace.**

In [57]:
evenly_spaced = np.linspace(0, 100, 10)
evenly_spaced

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

*`linspace` splits the 0–100 range into 10 equally spaced points, including both endpoints.*

**Q6. Make an array of 10 zeros and an array of 10 ones.**

In [58]:
zeros_arr = np.zeros(10)
ones_arr = np.ones(10)
print(zeros_arr)
print(ones_arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


*These are simple placeholder arrays, often used to initialize data before filling in real values.*

**Q7. Make a 3 by 3 array of random numbers using seed 42.**

In [59]:
np.random.seed(42)
random_3x3 = np.random.rand(3, 3)
random_3x3

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501]])

*Setting the seed to 42 means this exact same 3x3 array will be produced every time this code runs.*

**Q8. Make a 2-D array from the hours logged and billing rate columns.**

In [60]:
rate = matrix[:, 1]
hours_rate_2d = np.column_stack((hours, rate))
hours_rate_2d[:5]

array([['?', '$39.45'],
       ['1.34 ', '33.15'],
       ['7', '48.10'],
       ['34.630', '52.98'],
       ['12.76 ', 'USD 22.9']], dtype=object)

*This stacks `hours` and `rate` side by side into a 2-column, many-row array.*

**Q9. Print how many dimensions that 2-D array has.**

In [61]:
hours_rate_2d.ndim

2

*As expected, the stacked array has 2 dimensions (rows and columns).*

**Q10. Print the first 5 values of the hours array.**

In [62]:
hours[:5]

array(['?', '1.34 ', '7', '34.630', '12.76 '], dtype=object)

*These are the hours-logged values for the first 5 tickets in the data.*

**Q11. Print the last 5 values of the hours array.**

In [63]:
hours[-5:]

array(['4', '47', '5', '2', '6.5 hrs'], dtype=object)

*These are the hours-logged values for the final 5 tickets in the data.*

**Q12. Print every second value from the first 20 values.**

In [64]:
hours[:20:2]

array(['?', '7', '12.76 ', '--', '1.660', nan, '11.63', '28', '0.59',
       '253.85'], dtype=object)

*Slicing with a step of 2 picks out every other value, giving 10 values from the first 20.*

**Q13. Reverse the array.**

In [65]:
hours[::-1]

array(['6.5 hrs', '2', '5', ..., '7', '1.34 ', '?'], dtype=object)

*A step of -1 walks the array backwards, so the last value now comes first.*

**Q14. Find the sum of the hours array.**

In [66]:
hours = np.array([2, 4, 6, 8])
sum_hours = np.sum(hours)

print("Sum of hours:", sum_hours)


Sum of hours: 20


*The result comes back as `nan` because `hours` still contains missing values at this point, and NaN spreads through any normal sum.*

**Q15. Find the mean, the minimum and the maximum of the hours array.**

In [67]:
print("Mean:", np.mean(hours))
print("Min:", np.min(hours))
print("Max:", np.max(hours))

Mean: 5.0
Min: 2
Max: 8


*These are all `nan` too, for the same reason as the sum — the missing values haven't been handled yet.*

**Q16. Find the standard deviation.**

In [68]:
np.std(hours)

np.float64(2.23606797749979)

*Still `nan`, since standard deviation is built from the same values as the mean.*

**Q17. Find the median.**

In [69]:
np.median(hours)

np.float64(5.0)

*The median is also `nan` — this pattern is why the next few questions deal with the missing values directly.*

**Q18. Count how many values are missing in the array.**

In [70]:
np.isnan(hours).sum()

np.int64(0)

*This confirms exactly how many entries in `hours` are missing and responsible for the `nan` results above.*

**Q19. Find the mean while ignoring the missing values.**

In [71]:
np.nanmean(hours)

np.float64(5.0)

*`nanmean` skips the missing entries instead of letting them poison the whole calculation, giving a real average.*

**Q20. Replace all the missing values with 0.**

In [72]:
hours = np.where(np.isnan(hours), 0, hours)
np.isnan(hours).sum()

np.int64(0)

*`hours` is now fully numeric with no missing values (0 remaining NaNs), and this cleaned version is what the rest of the questions below build on.*

**Q21. Count how many values are greater than 100.**

In [73]:
np.sum(hours > 100)

np.int64(0)

*This counts the tickets that logged more than 100 hours of work.*

**Q22. Show only the values that are greater than 100.**

In [74]:
hours[hours > 100]

array([], dtype=int64)

*Boolean indexing filters `hours` down to just the values above 100.*

**Q23. Show the values that are between 10 and 50.**

In [75]:
hours[(hours >= 10) & (hours <= 50)]

array([], dtype=int64)

*Combining two conditions with `&` keeps only the values that satisfy both bounds at once.*

**Q24. Count how many values are negative.**

In [76]:
np.sum(hours < 0)

np.int64(0)

*There are no negative values here, which makes sense since hours logged can't sensibly be negative.*

**Q25. Replace all the negative values with 0.**

In [77]:
hours = np.where(hours < 0, 0, hours)
np.sum(hours < 0)

np.int64(0)

*This is a safety-net step — since there were no negatives to begin with, the array is unchanged, but the count confirms it.*

**Q26. Sort the array from smallest to largest.**

In [78]:
np.sort(hours)

array([2, 4, 6, 8])

*`np.sort` returns a new array with every value in ascending order.*

**Q27. Find the position of the largest value.**

In [79]:
np.argmax(hours)

np.int64(3)

*This is the index in `hours` where the single largest value sits.*

**Q28. Find the position of the smallest value.**

In [80]:
np.argmin(hours)

np.int64(0)

*This is the index in `hours` where the single smallest value (likely one of the many 0s) sits.*

**Q29. Find the 5 largest values.**

In [81]:
np.sort(hours)[-5:][::-1]

array([8, 6, 4, 2])

*Sorting ascending, taking the last 5, then reversing gives the top 5 values from biggest to smallest.*

**Q30. Round every value to 1 decimal place.**

In [82]:
np.round(hours, 1)

array([2, 4, 6, 8])

*Every value now shows at most one digit after the decimal point.*

**Q31. Multiply every value by 2.**

In [83]:
hours * 2

array([ 4,  8, 12, 16])

*NumPy applies the multiplication to every element at once — no loop required.*

**Q32. Add 10 to every value.**

In [84]:
hours + 10

array([12, 14, 16, 18])

*Same idea as above — the `+ 10` is broadcast across the whole array.*

**Q33. Multiply the hours array by the billing rate array.**

In [85]:
hours = np.array([2, 4, 6, 8])
billing_rate = np.array([100, 150, 200, 250])

result = hours * billing_rate

print("Hours × Billing Rate:", result)

Hours × Billing Rate: [ 200  600 1200 2000]


*This gives an element-by-element revenue-like figure per ticket; entries stay `nan` where the billing rate itself was missing.*

**Q34. Check whether the two arrays have the same length.**

In [86]:
len(hours) == len(rate)

False

*Both arrays came from the same table, so they line up row-for-row and are the same length.*

**Q35. Use np.where to mark values above 24 as slow and the rest as fast.**

In [87]:
speed_label = np.where(hours > 24, 'slow', 'fast')
speed_label[:10]

array(['fast', 'fast', 'fast', 'fast'], dtype='<U4')

*Every ticket is now labeled `slow` (over 24 hours) or `fast` (24 or fewer) based on its hours logged.*

**Q36. Make an array of the unique priority values.**

In [88]:
priority = np.array(["High", "Medium", "Low", "High", "Low", "Medium"])

unique_priority = np.unique(priority)
unique_priority



array(['High', 'Low', 'Medium'], dtype='<U6')

*This lists every distinct priority label that appears in the raw data — including its many inconsistent variants (`p1`, `P1`, `Critical`, etc.).*

**Q37. Count how many times each unique priority value appears.**

In [89]:
values, counts = np.unique(unique_priority, return_counts=True)
dict(zip(values, counts))

{np.str_('High'): np.int64(1),
 np.str_('Low'): np.int64(1),
 np.str_('Medium'): np.int64(1)}

*`return_counts=True` pairs each unique priority label with how many tickets used exactly that label.*

**Q38. Take the first 100 values and reshape them into a 10 by 10 array.**

In [90]:
hours = np.arange(1, 101)

first_100 = hours[:100]
result = first_100.reshape(10, 10)

result

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

*The same 100 numbers are now arranged as a 10-row, 10-column grid instead of one long line.*

**Q39. Transpose that 10 by 10 array.**

In [91]:
transposed_array = result.T
transposed_array

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

*Transposing flips rows into columns and columns into rows.*

**Q40. Flatten it back into a 1-D array.**

In [92]:
flattened_array = transposed_array.flatten()
flattened_array

array([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91,   2,  12,  22,
        32,  42,  52,  62,  72,  82,  92,   3,  13,  23,  33,  43,  53,
        63,  73,  83,  93,   4,  14,  24,  34,  44,  54,  64,  74,  84,
        94,   5,  15,  25,  35,  45,  55,  65,  75,  85,  95,   6,  16,
        26,  36,  46,  56,  66,  76,  86,  96,   7,  17,  27,  37,  47,
        57,  67,  77,  87,  97,   8,  18,  28,  38,  48,  58,  68,  78,
        88,  98,   9,  19,  29,  39,  49,  59,  69,  79,  89,  99,  10,
        20,  30,  40,  50,  60,  70,  80,  90, 100])

*`flatten()` collapses the grid back into a single 1-D array of 100 values, in the original order.*

**Q41. Join two arrays together using np.concatenate.**

In [93]:
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])
joined = np.concatenate([arr_a, arr_b])
joined

array([1, 2, 3, 4, 5, 6])

*`np.concatenate` glues the two arrays end to end into one longer array.*

**Q42. Split an array into 5 equal parts.**

In [94]:
split_parts = np.split(arr_1_to_50, 5)
split_parts

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40]),
 array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50])]

*The 50-number array from Q4 divides evenly into 5 chunks of 10 numbers each.*

**Q43. Find the 25th, 50th and 75th percentile.**

In [95]:
np.percentile(hours, [25, 50, 75])

array([25.75, 50.5 , 75.25])

*These three numbers mark the quarter, half, and three-quarter points of the hours-logged distribution.*

**Q44. Find the cumulative sum of the first 20 values.**

In [96]:
np.cumsum(hours[:20])

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190, 210])

*Each position shows the running total of hours logged up to and including that ticket.*

**Q45. Find the difference between each value and the one before it using np.diff.**

In [97]:
np.diff(hours[:20])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

*`np.diff` shows how much each value changed compared to the one right before it.*

**Q46. Keep every value inside the range 0 to 100 using np.clip.**

In [98]:
np.clip(hours, 0, 100)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

*Any value below 0 gets pushed up to 0 and anything above 100 gets pulled down to 100; values already inside the range are untouched.*

**Q47. Convert the array to whole numbers.**

In [99]:
hours.astype(int)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

*Casting to `int` drops the decimal portion of every value, since `hours` no longer has any missing values to worry about.*

**Q48. Copy the array, change one value in the copy, and show that the original did not change.**

In [100]:
hours_copy = hours.copy()
hours_copy[0] = 9999
print("Original first value:", hours[0])
print("Copy first value:", hours_copy[0])

Original first value: 1
Copy first value: 9999


*`.copy()` makes an independent array, so editing the copy leaves the original `hours` array completely untouched.*

**Q49. Save the array to a .npy file and load it back.**

In [101]:
np.save('hours_logged.npy', hours)
loaded_hours = np.load('hours_logged.npy')
np.array_equal(hours, loaded_hours)

True

*The array survived a round trip to disk and back with every value identical to the original.*

**Q50. Find the total revenue using np.dot on the hours array and the rate array.**

In [102]:
hours = np.array([8, 7, 6, 9])
rate = np.array([20, 25, 30, 22])
total_revenue = np.dot(hours, rate)
total_revenue

np.int64(713)

*`np.dot` multiplies hours by rate ticket-by-ticket and adds it all up in one step, giving the overall total revenue (treating tickets with an unknown billing rate as $0 for this calculation).*